version: "3.9"

services:
    web:
        image: nginx:1.25.3-alpine
        ports:
            - "8080:80"
        volumes:
            - ./public:/app/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./:/app
        environment:
            XDEBUG_MODE: debug,coverage
            XDEBUG_SESSION: PHPSTORM
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        depends_on:
            - postgres

    postgres:
        image: postgres:16.1-alpine
        environment:
            POSTGRES_USER: web-app
            POSTGRES_PASSWORD: web-app
            POSTGRES_DB: web-app
        volumes:
            - ./docker/data/db:/var/lib/postgresql/data
        ports:
            - "15432:5432"
